Kütüphanenin Eklenmesi ve Verinin Okunması

In [1]:
import pandas as pd

df = pd.read_csv('twitter_data.csv')
print("Veriseti boyutu:", df.shape)

Veriseti boyutu: (14640, 15)

Verisetinin İncelenmesi

In [2]:
print("Sütun İsimleri:", df.columns.tolist())
print("\nVeri Türleri:", df.dtypes)
df.head()

Sütun İsimleri: ['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence', 'negativereason', 'negativereason_confidence', 'airline', 'airline_sentiment_gold', 'name', 'negativereason_gold', 'retweet_count', 'text', 'tweet_coord', 'tweet_created', 'tweet_location', 'user_timezone']

Veri Türleri: tweet_id                          int64
airline_sentiment                object
airline_sentiment_confidence    float64
negativereason                   object
negativereason_confidence       float64
airline                          object
airline_sentiment_gold           object
name                             object
negativereason_gold              object
retweet_count                     int64
text                             object
tweet_coord                      object
tweet_created                    object
tweet_location                   object
user_timezone                    object
dtype: object

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [3]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   tweet_id                      14640 non-null  int64
 1   airline_sentiment             14640 non-null  object
 2   airline_sentiment_confidence  14640 non-null  float64
 3   negativereason                9178 non-null   object
 4   negativereason_confidence     10522 non-null  float64
 5   airline                       14640 non-null  object
 6   airline_sentiment_gold        40 non-null     object
 7   name                          14640 non-null  object
 8   negativereason_gold           32 non-null     object
 9   retweet_count                 14640 non-null  int64
 10  text                          14640 non-null  object
 11  tweet_coord                   1019 non-null   object
 12  tweet_created                 14640 non-null  object
 13  tweet_location                9907 non-null   object
 14  user_timezone                 9820 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 1.7+ MB

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
count,1.464000e+04,14640,14640.000000,9178,10522.000000,14640,40,14640,32,14640.000000,14640,1019,14640,9907,9820
unique,NaN,3,NaN,10,NaN,6,3,7701,13,NaN,14427,832,14247,3081,85
top,NaN,negative,NaN,Customer Service Issue,NaN,United,negative,JetBlueNews,Customer Service Issue,NaN,@united thanks,"[0.0, 0.0]",2015-02-24 09:54:34 -0800,"Boston, MA",Eastern Time (US & Canada)
freq,NaN,9178,NaN,2910,NaN,3822,32,63,12,NaN,6,164,5,157,3744
mean,5.692184e+17,NaN,0.900169,NaN,0.638298,NaN,NaN,NaN,NaN,0.082650,NaN,NaN,NaN,NaN,NaN
std,7.791112e+14,NaN,0.162830,NaN,0.330440,NaN,NaN,NaN,NaN,0.745778,NaN,NaN,NaN,NaN,NaN
min,5.675883e+17,NaN,0.335000,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
25%,5.685592e+17,NaN,0.692300,NaN,0.360600,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
50%,5.694779e+17,NaN,1.000000,NaN,0.670600,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
75%,5.698905e+17,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
max,5.703106e+17,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,NaN,44.000000,NaN,NaN,NaN,NaN,NaN

Tekrarlanan kayıtların silinmesi

In [4]:
baslangic_kayit_sayisi = df.shape[0]

print("Tekrarlanan kayıt sayısı:", df.duplicated().sum())
df = df.drop_duplicates().copy()
print("Tekrarlanan kayıtlar silindikten sonra boyut:", df.shape)

Tekrarlanan kayıt sayısı: 36
Tekrarlanan kayıtlar silindikten sonra boyut: (14604, 15)

Regex ile Metin Temizleme

In [5]:
import re

def clean_text(text):
    if type(text) == str:
        text = re.sub(r'http\S+', '', text)
        text = re.sub(r'@\w+', '', text)
        text = re.sub(r'#\w+', '', text)
        text = re.sub(r'[^\w\s]', '', text)
        text = text.strip()
    return text

df['clean_text'] = df['text'].apply(clean_text)
df[['text', 'clean_text']].head()

,text,clean_text
0,@VirginAmerica What @dhepburn said.,What said
1,@VirginAmerica plus you've added commercials t...,plus youve added commercials to the experience...
2,@VirginAmerica I didn't today... Must mean I n...,I didnt today Must mean I need to take another...
3,@VirginAmerica it's really aggressive to blast...,its really aggressive to blast obnoxious enter...
4,@VirginAmerica and it's a really big bad thing...,and its a really big bad thing about it

Eksik değerlerin giderilmesi

In [6]:
print("Eksik değer sayısı:", df.isnull().sum())
if 'negativereason' in df.columns:
    df['negativereason'] = df['negativereason'].fillna('Not Specified')
df = df.dropna(subset=['clean_text', 'airline_sentiment'])
print("\nEksik veriler işlendikten sonra boyut:", df.shape)

Eksik değer sayısı: tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5445
negativereason_confidence        4101
airline                             0
airline_sentiment_gold          14564
name                                0
negativereason_gold             14572
retweet_count                       0
text                                0
tweet_coord                     13589
tweet_created                       0
tweet_location                   4723
user_timezone                    4814
clean_text                          0
dtype: int64

Eksik veriler işlendikten sonra boyut: (14604, 16)

Veri Tiplerinin kontrol edilmesi

In [7]:
if 'tweet_created' in df.columns:
    df['tweet_created'] = pd.to_datetime(df['tweet_created'], errors='coerce')
print("Güncel veri tipleri:\n", df.dtypes)

Güncel veri tipleri:
 tweet_id                                            int64
airline_sentiment                                  object
airline_sentiment_confidence                      float64
negativereason                                     object
negativereason_confidence                         float64
airline                                            object
airline_sentiment_gold                             object
name                                               object
negativereason_gold                                object
retweet_count                                       int64
text                                               object
tweet_coord                                        object
tweet_created                   datetime64[ns, UTC-08:00]
tweet_location                                     object
user_timezone                                      object
clean_text                                         object
dtype: object

In [8]:
son_kayit_sayisi = df.shape[0]
print(f"Temizleme Öncesi Kayıt Sayısı: {baslangic_kayit_sayisi}")
print(f"Temizleme Sonrası Kayıt Sayısı: {son_kayit_sayisi}")
print(f"Toplam {baslangic_kayit_sayisi - son_kayit_sayisi} kayıt pipeline'ın bu adımında temizlendi.")

Temizleme Öncesi Kayıt Sayısı: 14640
Temizleme Sonrası Kayıt Sayısı: 14604
Toplam 36 kayıt pipeline'ın bu adımında temizlendi.

MongoDB Bağlantısı ve Bulk Insert

In [9]:
from pymongo import MongoClient
import pandas as pd

atlas_uri = "ATLAS URI
client = MongoClient(atlas_uri)
db = client['twitter_db']
collection = db['tweetler']
collection.delete_many({})

if 'tweet_created' in df.columns:
    df['tweet_created'] = df['tweet_created'].astype(str)

records = df.to_dict(orient='records')
collection.insert_many(records)

print(f"MongoDB Atlas'a {collection.count_documents({})} adet kayıt başarıyla eklendi!")

MongoDB Atlas'a 14604 adet kayıt başarıyla eklendi!

find() ile Temel Sorgular (3 Adet)

In [10]:
print("1)Sadece 'negative' olan 3 tweeti getir\n")
q1 = collection.find({'airline_sentiment': 'negative'}).limit(3)
for doc in q1: 
    print("-", doc.get('clean_text', ''))

print("\n2)'Virgin America' havayolunun tweetleri\n")
q2 = collection.find({'airline': 'Virgin America'}, {'_id': 0, 'clean_text': 1}).limit(3)
for doc in q2: 
    print("-", doc)

print("\n3)Güven skoru 0.9'dan büyük olan pozitif tweetler\n")
q3 = collection.find({
    'airline_sentiment': 'positive', 
    'airline_sentiment_confidence': {'$gt': 0.9}
}).limit(2)
for doc in q3: 
    print("- Havayolu:", doc.get('airline'), "| Metin:", doc.get('clean_text', ''))

1)Sadece 'negative' olan 3 tweeti getir

- its really aggressive to blast obnoxious entertainment in your guests faces amp they have little recourse
- and its a really big bad thing about it
- seriously would pay 30 a flight for seats that didnt have this playing
its really the only bad thing about flying VA

2)'Virgin America' havayolunun tweetleri

- {'clean_text': 'What  said'}
- {'clean_text': 'plus youve added commercials to the experience tacky'}
- {'clean_text': 'I didnt today Must mean I need to take another trip'}

3)Güven skoru 0.9'dan büyük olan pozitif tweetler

- Havayolu: Virgin America | Metin: it was amazing and arrived an hour early Youre too good to me
- Havayolu: Virgin America | Metin: I lt3 pretty graphics so much better than minimal iconography D

Aggregation Pipeline (3 Adet)

In [11]:
print("4. Havayollarına göre toplam tweet sayıları\n")
agg1 = collection.aggregate([{'$group': {'_id': '$airline', 'toplam_tweet': {'$sum': 1}}}])
for doc in agg1: print(doc)

print("\n5. Genel duygu dağılımı (Pozitif/Negatif/Nötr oranları)\n")
agg2 = collection.aggregate([{'$group': {'_id': '$airline_sentiment', 'adet': {'$sum': 1}}}])
for doc in agg2: print(doc)

print("\n6. En çok şikayet edilen 3 negatif sebep\n")
agg3 = collection.aggregate([
    {'$match': {'negativereason': {'$ne': 'Not Specified'}}},
    {'$group': {'_id': '$negativereason', 'frekans': {'$sum': 1}}},
    {'$sort': {'frekans': -1}},
    {'$limit': 3}
])
for doc in agg3: print(doc)

4. Havayollarına göre toplam tweet sayıları

{'_id': 'Virgin America', 'toplam_tweet': 504}
{'_id': 'Southwest', 'toplam_tweet': 2420}
{'_id': 'United', 'toplam_tweet': 3822}
{'_id': 'Delta', 'toplam_tweet': 2222}
{'_id': 'American', 'toplam_tweet': 2723}
{'_id': 'US Airways', 'toplam_tweet': 2913}

5. Genel duygu dağılımı (Pozitif/Negatif/Nötr oranları)

{'_id': 'neutral', 'adet': 3091}
{'_id': 'positive', 'adet': 2354}
{'_id': 'negative', 'adet': 9159}

6. En çok şikayet edilen 3 negatif sebep

{'_id': 'Customer Service Issue', 'frekans': 2904}
{'_id': 'Late Flight', 'frekans': 1660}
{'_id': "Can't Tell", 'frekans': 1190}

İndeks Oluşturma ve Test (1 Adet)

In [12]:
print("7. 'airline' alanına indeks oluşturma ve explain() analizi\n")
collection.create_index('airline')

sorgu_plani = collection.find({'airline': 'United'}).explain()

print("Kullanılan indeks (Winning Plan):")
print(sorgu_plani['queryPlanner']['winningPlan'])

7. 'airline' alanına indeks oluşturma ve explain() analizi

Kullanılan indeks (Winning Plan):
{'isCached': False, 'stage': 'FETCH', 'inputStage': {'stage': 'IXSCAN', 'keyPattern': {'airline': 1}, 'indexName': 'airline_1', 'isMultiKey': False, 'multiKeyPaths': {'airline': []}, 'isUnique': False, 'isSparse': False, 'isPartial': False, 'indexVersion': 2, 'direction': 'forward', 'indexBounds': {'airline': ['["United", "United"]']}}}

UPDATE İşlemleri (2 Adet)

In [13]:
print("8. UPDATE: İlk United Airlines tweetinin retweet sayısını $inc ile 5 artırma\n")

query = {'airline': 'United'}
fields = {'_id': 1,'airline': 1,'retweet_count': 1}
print(list(collection.find(query, fields).limit(1)))

res1 = collection.update_one({'airline': 'United'}, {'$inc': {'retweet_count': 5}})
print(f"Değiştirilen doküman sayısı: {res1.modified_count}")

query = {'airline': 'United'}
fields = {'_id': 1,'airline': 1,'retweet_count': 1}
print(list(collection.find(query, fields).limit(1)))

print("\n9. UPDATE: 'neutral' olan tweetlere $set ile 'is_analyzed' alanı ekleme\n")
res2 = collection.update_many({'airline_sentiment': 'neutral'}, {'$set': {'is_analyzed': True}})
print(f"Güncellenen nötr tweet sayısı: {res2.modified_count}\n")

updated_docs = collection.find({'airline_sentiment': 'neutral', 'is_analyzed': True},{'_id': 0, 'text': 1, 'airline_sentiment': 1, 'is_analyzed': 1}).limit(3)

for doc in updated_docs:
    print(doc)

8. UPDATE: İlk United Airlines tweetinin retweet sayısını $inc ile 5 artırma

[{'_id': ObjectId('6a21738aec2494ab29b91d42'), 'airline': 'United', 'retweet_count': 0}]
Değiştirilen doküman sayısı: 1
[{'_id': ObjectId('6a21738aec2494ab29b91d42'), 'airline': 'United', 'retweet_count': 5}]

9. UPDATE: 'neutral' olan tweetlere $set ile 'is_analyzed' alanı ekleme

Güncellenen nötr tweet sayısı: 3091

{'airline_sentiment': 'neutral', 'text': '@VirginAmerica What @dhepburn said.', 'is_analyzed': True}
{'airline_sentiment': 'neutral', 'text': "@VirginAmerica I didn't today... Must mean I need to take another trip!", 'is_analyzed': True}
{'airline_sentiment': 'neutral', 'text': '@VirginAmerica Really missed a prime opportunity for Men Without Hats parody, there. https://t.co/mWpG7grEZP', 'is_analyzed': True}

DELETE ve İleri Seviye Serbest Sorgular (3 Adet)

In [14]:
print("10. DELETE: Güven skoru 0.4'ten küçük olan düşük kaliteli verileri silme\n")
silme_islemi = collection.delete_many({'airline_sentiment_confidence': {'$lt': 0.4}})
print(f"Silinen düşük kaliteli kayıt sayısı: {silme_islemi.deleted_count}")

print("\n11. REGEX: İçinde 'delay' veya 'delayed' geçen tweetler\n")
q11 = collection.find({'clean_text': {'$regex': 'delay', '$options': 'i'}}).limit(3)
for doc in q11: 
    print("-", doc.get('clean_text', ''))

print("\n12. İÇ İÇE: Retweet edilmiş ve Eastern Time zone'da atılmış tweetler\n")
q12 = collection.find({'retweet_count': {'$gt': 0}, 'user_timezone': 'Eastern Time (US & Canada)'}).limit(2)
for doc in q12: 
    print(f"- {doc.get('airline')} (RT: {doc.get('retweet_count')})")

10. DELETE: Güven skoru 0.4'ten küçük olan düşük kaliteli verileri silme

Silinen düşük kaliteli kayıt sayısı: 236

11. REGEX: İçinde 'delay' veya 'delayed' geçen tweetler

- youre the best Whenever I begrudgingly use any other airline Im delayed and Late Flight
- should I be concerned that I am about to fly on a plane that needs to be delayed due to a tech stop
- Love the team running Gate E9 at LAS tonight Waited for a delayed flight and they kept things entertaining

12. İÇ İÇE: Retweet edilmiş ve Eastern Time zone'da atılmış tweetler

- United (RT: 1)
- United (RT: 1)

PySpark Ortamının Kurulması ve Verinin yüklenmesi

In [ ]:
#!pip install pyspark
import os
os.environ["JAVA_HOME"] = r"C:\Program Files\Eclipse Adoptium\jdk-17.0.11.9-hotspot"

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("TwitterAnalysis").getOrCreate()

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("TwitterAnalysis").getOrCreate()
spark_df = spark.createDataFrame(df)
spark_df.printSchema()

Dönüşüm (Transformation) İşlemleri (3 Adet)

In [ ]:
from pyspark.sql.functions import length

print("1. Transformation: select() ve filter()")
# Sadece United havayoluna ait negatif tweetleri filtreleyip seçme
negatif_united = spark_df.select("airline", "clean_text", "airline_sentiment") \
                         .filter((spark_df.airline == "United") & (spark_df.airline_sentiment == "negative"))
negatif_united.show(3, truncate=False)

print("\n2. Transformation: withColumn()")
# Tweet metninin karakter uzunluğunu yeni bir sütun olarak ekleme
spark_df = spark_df.withColumn("tweet_uzunlugu", length(spark_df.clean_text))
spark_df.select("clean_text", "tweet_uzunlugu").show(3)

print("\n3. Transformation: groupBy()")
# Havayollarına göre toplam tweet sayılarını gruplama
havayolu_grup = spark_df.select("airline").coalesce(1).groupBy("airline").count()
havayolu_grup.show(3)